"""Generated by Django 3.0.5 on 2020-04-26 14:18"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image',
                 models.ImageField(null=True, upload_to='product_images/')),
                ('description', models.TextField()),
                ('school_type', models.CharField(
                    choices=[('PR', 'praktijkonderwijs'), ('VM', 'vmbo'),
                             ('MB', 'mbo'), ('HB', 'hbo'),
                             ('OP', 'opleidingsbedrijf')], max_length=2)),
                ('price', models.FloatField()),
                ('publishing_end_date', models.DateTimeField()),
                ('categories', models.ManyToManyField(to='products.Category')),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='products.Company')),
            ],
        ),
    ]
